export const exampleStyle = `
  --primary: #440381;
  --secondary: #ffcc66;
  --dark: #161124;
  --light: #f2edeb;
  --canvas: #ffffff;
  --primary-text: white;
  --primary-confirm: #00cc55;
  --primary-warn: #ff6090;
  --secondary-text: var(--dark);
  --secondary-confirm: #165a2d;
  --secondary-warn: #a40e36;
  --dark-confirm: #00cc53;
  --dark-warn: #ff5557;
  --a11y-link: #0066cc;
  --dark-link: #21b2fa;
  --button-target-size: 2.5em;
  --body-font-family: Source Sans Pro;
  --header-font-family: var(--body-font-family);
  --button-font-family: var(--body-font-family);
  --body-line-height: 1.5;
  --header-line-height: 1.13;
  --article-sidebar-width: 200px;
  --text-shadow-hsl: 0 0% 0%;
  --modal-overlay-color: black;
  --modal-overlay-opacity: 0.75;
  font-family: var(--body-font-family);
  line-height: var(--body-line-height);
`;
